import { useState, type FormEvent, type ReactNode } from 'react'

const updated = '22 Eylül 2026'
const Arrow = () => <span aria-hidden="true">↗</span>

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="site-header"><a className="logo" href="/"><span>YZ</span><b>Yapay Zekâda<br/>Reklam</b></a><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open}>Menü</button><nav className={open ? 'nav open' : 'nav'}><a href="/yapay-zeka-platformlarinda-reklam/">AI Reklamları</a><a href="/chatgpt-reklamlari/">ChatGPT Ads</a><a href="/geo-yapay-zeka-gorunurlugu/">AI Görünürlüğü</a><a href="/blog/">Kaynaklar</a><a className="nav-cta" href="/iletisim/">Ücretsiz ön analiz <Arrow/></a></nav></header>
}

function Footer() {
  return <footer className="site-footer"><div className="footer-lead"><span className="kicker">Bir sonraki karar anı</span><h2>Müşteriniz sorarken<br/>markanız orada olsun.</h2><a className="button light" href="/iletisim/">İlk test planını çıkaralım <Arrow/></a></div><div className="footer-grid"><div><strong>Yapay Zekâda Reklam</strong><p>AI reklam yönetimi ve GEO danışmanlığı.</p></div><div><strong>Hizmetler</strong><a href="/chatgpt-reklamlari/">ChatGPT Ads</a><a href="/geo-yapay-zeka-gorunurlugu/">GEO</a></div><div><strong>Şirket</strong><a href="/hakkimizda/">Hakkımızda</a><a href="/iletisim/">İletişim</a></div><div><strong>Yasal</strong><a href="/gizlilik/">Gizlilik</a><a href="/kvkk/">KVKK</a></div></div><div className="footer-bottom"><span>© 2026 Yapay Zekâda Reklam · Bir <a href="https://overseas.marketing" target="_blank" rel="noreferrer">overseas.marketing</a> markasıdır.</span><span>Güncelleme: {updated}</span></div></footer>
}
const Layout = ({children}:{children:ReactNode}) => <><Header/>{children}<Footer/></>
const services = [
  ['01','ChatGPT Ads yönetimi','Hesap, kampanya, context hints, reklam, landing page ve dönüşüm ölçümünü tek performans sistemi olarak kuruyoruz.','/chatgpt-reklamlari/'],
  ['02','AI platformlarında reklam','ChatGPT, Google AI Mode, Copilot ve gelişen reklam yüzeylerini erişim ve ölçüm imkânlarına göre planlıyoruz.','/yapay-zeka-platformlarinda-reklam/'],
  ['03','GEO ve organik görünürlük','Markanızın yapay zekâ sistemleri tarafından anlaşılması ve güvenilir kaynak olarak değerlendirilmesi için çalışıyoruz.','/geo-yapay-zeka-gorunurlugu/'],
  ['04','AI destekli kreatif','Farklı karar bağlamları için marka dili ve insan kontrolüyle nitelikli reklam varyasyonları üretiyoruz.','/yapay-zeka-ile-reklam-uretimi/']
]
const faqs = [
  ['Yapay zekâda reklam vermek ne demektir?','ChatGPT, Google AI Mode ve Copilot gibi yapay zekâ destekli deneyimlerde sunulan sponsorlu alanlarda kampanya yayınlamaktır.'],
  ['ChatGPT reklamı ile organik cevap aynı mı?','Hayır. Sponsorlu reklam ile organik yapay zekâ cevabı ayrı sistemlerdir; reklamveren organik cevabı satın alamaz.'],
  ['Context hints nedir?','Ürününüzün kim için ve hangi durumda faydalı olduğunu doğal dille açıklayan bağlam ipuçlarıdır; klasik anahtar kelime değildir.'],
  ['GEO hizmeti nedir?','Marka ve içeriğin AI sistemlerince anlaşılması, doğrulanması ve uygun cevaplarda kaynak olarak değerlendirilmesi için yapılan çalışmalardır.']
]

function Home(){return <Layout><main><section className="hero section-pad"><div className="hero-copy"><div className="status"><i/>ChatGPT Ads + GEO · {updated}</div><h1>Karar anında<br/><em>görünün.</em></h1><p className="hero-text">ChatGPT Ads başta olmak üzere yeni nesil yapay zekâ reklam kanallarında strateji, kurulum, içerik, ölçümleme ve sürekli optimizasyon.</p><div className="button-row"><a className="button primary" href="/iletisim/">Ücretsiz ön analiz <Arrow/></a><a className="text-link" href="/chatgpt-reklamlari/">ChatGPT reklamlarını inceleyin <Arrow/></a></div><div className="trust-line"><span>Strateji</span><span>Kurulum</span><span>Kreatif</span><span>Ölçüm</span><span>Optimizasyon</span></div></div><div className="hero-visual"><img src="/images/ai-karar-aninda-reklam.png" alt="Yapay zekâ bağlamlarının karar anına dönüştüğü soyut görsel" fetchPriority="high"/><div className="signal-card"><span>Sponsorlu görünürlük</span><b>Organik cevaptan ayrıdır.</b></div></div></section>
<section className="context section-pad"><div className="section-label">01 / Yeni karar yüzeyi</div><div className="context-grid"><h2>Müşteriniz yapay zekâya sorarken markanız nerede?</h2><div><blockquote>“50 kişilik satış ekibimiz için kurulumu kolay, Türkçe destek sunan ve mevcut CRM’imizle entegre olabilen bir çözüm arıyorum.”</blockquote><p>Kısa anahtar kelimelerin yerini ayrıntılı ihtiyaçlar alıyor. Yeni birim yalnızca arama sözcüğü değil; <strong>durum, niyet ve konuşma bağlamı.</strong></p></div></div><div className="context-strip"><span>İhtiyaç</span><b>→</b><span>Bağlam</span><b>→</b><span>Karşılaştırma</span><b>→</b><span>Karar</span></div></section>
<section className="services section-pad"><div className="section-heading"><div><div className="section-label">02 / Hizmetler</div><h2>Reklam paneli değil,<br/>karar bağlamı yönetiyoruz.</h2></div><p>Teklif, bağlam, kreatif, landing page ve dönüşüm verisini aynı sistemin parçaları olarak ele alıyoruz.</p></div><div className="service-grid">{services.map((s,i)=><a className={'service-card '+(!i?'featured':'')} href={s[3]} key={s[0]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><Arrow/></a>)}</div></section>
<section className="process section-pad"><div className="section-label">03 / Süreç</div><h2>Bir kampanyadan daha fazlası:<br/>ölçülebilir bir öğrenme sistemi.</h2><div className="steps">{['Talep ve bağlam','Teklif ve sayfa','Kampanya kurulumu','Kreatif varyasyon','Dönüşüm ölçümü','Optimizasyon'].map((x,i)=><div className="step" key={x}><span>0{i+1}</span><h3>{x}</h3></div>)}</div></section>
<section className="difference section-pad"><div className="section-label">04 / Net ayrım</div><h2>Reklam görünürlük satın alır.<br/><em>GEO güven inşa eder.</em></h2><div className="difference-grid"><article><span>Ücretli</span><h3>ChatGPT Ads</h3><p>Sponsorlu, açıkça etiketlenen reklam alanı. Bütçe, reklam grupları, teklifler ve ölçümleme üzerinden yönetilir.</p><a href="/chatgpt-reklamlari/">ChatGPT Ads’i keşfedin <Arrow/></a></article><article><span>Organik</span><h3>GEO</h3><p>Markanızın yapay zekâ sistemlerince anlaşılmasını ve güvenilir kaynak olarak değerlendirilmesini destekler.</p><a href="/geo-yapay-zeka-gorunurlugu/">GEO yaklaşımımız <Arrow/></a></article></div><p className="disclaimer">Reklam satın almak, yapay zekâ sistemlerinin organik cevabını değiştirme hakkı vermez.</p></section>
<section className="principles section-pad"><div className="section-heading"><div><div className="section-label">05 / Yaklaşım</div><h2>Yeni kanalda eski<br/>ezberlerle ilerlemeyin.</h2></div><p>Önce uygunluğu ve ölçülebilirliği kontrol eder, sonra kontrollü test kurarız.</p></div><div className="principle-list">{[['Doğruluk','Sunmadığınız faydayı vaat etmeyiz.'],['Bağlam','Gerçek kullanım durumlarını ayırırız.'],['Ölçüm','Tıklamayı iş hedefiyle ilişkilendiririz.'],['Şeffaflık','Erişime açık olmayan özelliği satmayız.']].map((x,i)=><div key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>
<section className="faq section-pad"><div className="section-label">06 / SSS</div><div className="faq-grid"><h2>Kısa ve net<br/>cevaplar.</h2><div>{faqs.map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></div></section></main></Layout>}

type DetailProps={eyebrow:string,title:string,summary:string,children:ReactNode,cta?:string}
function Detail({eyebrow,title,summary,children,cta='Ücretsiz ön analiz isteyin'}:DetailProps){return <Layout><main><section className="detail-hero section-pad"><div className="status"><i/>{eyebrow} · {updated}</div><h1>{title}</h1><p>{summary}</p><a className="button primary" href="/iletisim/">{cta} <Arrow/></a></section><section className="detail-body section-pad">{children}</section></main></Layout>}
const Features=({items}:{items:[string,string][]})=><div className="feature-grid">{items.map((x,i)=><article key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div>

const pages:{[key:string]:{e:string,t:string,s:string,items:[string,string][]}}={
 '/chatgpt-reklamlari':{e:'Ana hizmet',t:'ChatGPT Reklam Ajansı ve Uçtan Uca Ads Yönetimi',s:'ChatGPT reklamları uygun konuşma bağlamlarında organik cevaptan ayrı gösterilen sponsorlu alanlardır. Niyet, context hints, reklam, landing page ve dönüşüm ölçümünü tek sistem olarak yönetiyoruz.',items:[['Hesap ve işletme kurulumu','Ads Manager, doğrulama, ekip erişimleri ve politika ön kontrolü.'],['Kampanya stratejisi','Hedef, ülke, bütçe ve öğrenme süresi planı.'],['Context hints','İhtiyaçları doğal, doğru bağlam açıklamalarına dönüştürme.'],['Ölçümleme','Pixel, Conversions API, UTM, analitik ve CRM eşleştirmesi.']]},
 '/yapay-zeka-platformlarinda-reklam':{e:'Kanal stratejisi',t:'Yapay Zekâ Platformlarında Reklam Verme',s:'Her AI platformunun erişimi, formatı ve ölçüm araçları farklıdır. Tek kampanyayı bütün kanallara kopyalamak yerine platform bazlı strateji kuruyoruz.',items:[['ChatGPT Ads','Konuşma bağlamı ve dönüşüm ölçümünün birlikte planlandığı ana uzmanlık alanımız.'],['Google AI Mode','Google Ads altyapısı, ürün verisi ve landing page hazırlığı.'],['Microsoft Copilot','Microsoft Advertising ve Bing ekosistemindeki uygun AI yüzeyleri.'],['Perplexity ve diğerleri','Erişim yoksa reklam vaadi değil; hazırlık ve organik görünürlük.']]},
 '/geo-yapay-zeka-gorunurlugu':{e:'Organik görünürlük',t:'Yapay Zekâ Aramalarında Görünürlük: GEO',s:'GEO; markanızın üretken yapay zekâ sistemleri tarafından anlaşılması ve uygun cevaplarda güvenilir kaynak olarak değerlendirilebilmesi için yapılan teknik, içerik ve otorite çalışmalarıdır.',items:[['Varlık netliği','Marka, ürün ve hizmet bilgilerinin tutarlı tanımı.'],['Cevap mimarisi','Kaynak gösterilebilir cevaplar ve özgün rehberler.'],['Teknik erişim','Taranabilirlik, bot erişimi, schema ve iç link yapısı.'],['Sürekli ölçüm','Marka geçişi, kaynak görünümü ve rakip karşılaştırması.']]},
 '/yapay-zeka-ile-reklam-uretimi':{e:'AI destekli üretim',t:'Yapay Zekâ ile Reklam Üretimi',s:'Yapay zekâyı tek tuşla içerik için değil; güçlü fikri farklı karar bağlamlarında hızla çeşitlendirmek, test etmek ve geliştirmek için kullanıyoruz.',items:[['Önce strateji','Ürün, hedef kitle, fayda ve dönüşüm hedefi netleşir.'],['Gerçek varyasyon','Aynı fikri çoğaltmak yerine farklı hipotezler test edilir.'],['İnsan kontrolü','Marka tonu, doğruluk, telif ve etik incelenir.'],['Performans döngüsü','Kazanan mesajlar yeni varyasyonlara dönüşür.']]},
 '/hakkimizda':{e:'Hakkımızda',t:'Yeni Reklam Çağını Öğreniyor, Test Ediyor ve Ölçüyoruz',s:'Yapay Zekâda Reklam, markaların gelişen yapay zekâ destekli keşif kanallarında ücretli ve organik görünürlük kazanmasına yardımcı olan bağımsız bir uzmanlık markasıdır.',items:[['Doğru teklif','Sunulmayan faydayı vaat etmeyen teklifler.'],['Gerçek niyet','Kelime listeleri yerine karar bağlamlarını anlama.'],['Ölçülebilir sonuç','Tıklamanın ötesinde lead ve satış etkisi.']]}
}
function GenericPage({data}:{data:typeof pages[string]}){return <Detail eyebrow={data.e} title={data.t} summary={data.s}><Features items={data.items}/><div className="prose-lead"><h2>Doğruluk ve şeffaflık</h2><p>Platformların erişimi ve özellikleri değişebilir. Güncel durumu birincil kaynaklardan doğrular, sponsorlu reklam ile organik cevabı açıkça ayırırız.</p></div></Detail>}
function Guide(){const steps=['Uygunluğu doğrulayın','Ads Manager hesabını açın','Kampanya hedefini seçin','Reklam gruplarını ayırın','Context hints yazın','Reklamları hazırlayın','Landing page’i eşleştirin','Pixel ve API’yi bağlayın','İlk veriyi yorumlayın'];return <Detail eyebrow="2026 rehberi" title="ChatGPT’ye Reklam Nasıl Verilir?" summary="ChatGPT’ye reklam vermek için hesap, kampanya, reklam grubu ve reklam yapısı Ads Manager üzerinden kurulur. Sistem klasik anahtar kelime mantığının kopyası gibi değil; niyet, bağlam ve ölçümle planlanmalıdır."><div className="timeline">{steps.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,'0')}</span><h3>{x}</h3></div>)}</div><aside className="note"><strong>Son kontrol: {updated}</strong><p>Ülke ve hesap erişimini resmî platform kaynaklarından doğrulayın.</p></aside></Detail>}
function Contact(){const [sent,setSent]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};return <Detail eyebrow="İletişim" title="Markanız İçin Doğru AI Reklam Planını Çıkaralım" summary="Kullanılabilir kanalı, gerekli hazırlığı ve ilk kontrollü testin hedefini birlikte netleştirelim.">{sent?<div className="success"><h2>Talebiniz ulaştı.</h2><p>Hedeflerinizi inceleyerek sizinle iletişime geçeceğiz.</p></div>:<form onSubmit={submit}><label>Ad soyad<input required/></label><label>İş e-postası<input required type="email"/></label><label>Şirket / web sitesi<input/></label><label>Öncelikli hedef<select><option>Lead</option><option>Satış</option><option>Görünürlük</option></select></label><label className="wide">Hedefiniz<textarea rows={4}/></label><label className="consent wide"><input required type="checkbox"/> KVKK metnini okudum.</label><button className="button primary">Ön analiz isteyin <Arrow/></button></form>}</Detail>}
function Blog(){return <Detail eyebrow="Bilgi merkezi" title="Yapay Zekâ Reklamcılığı Kaynakları" summary="Platform değişikliklerini, kampanya kurulumunu, ölçümlemeyi ve organik AI görünürlüğünü birincil kaynaklarla açıklayan güncel rehberler."><div className="post-grid">{['ChatGPT Reklamları Nedir?','Context Hints Nedir?','ChatGPT Ads ve GEO Farkı','Dönüşüm Takibi Rehberi','AI Reklam Ajansı Seçimi','Hazırlık Kontrol Listesi'].map((x,i)=><article key={x}><span>Rehber · 0{i+1}</span><h2>{x}</h2><p>Doğrudan cevap, uygulama adımları ve güncel platform durumu.</p></article>)}</div></Detail>}
function Legal({title}:{title:string}){return <Detail eyebrow="Yasal" title={title} summary="Bu alan gerçek şirket bilgileri ve sitenin veri akışıyla birlikte yayın öncesinde hukuk danışmanı tarafından tamamlanmalıdır."><div className="prose-lead"><h2>Şeffaflık ilkesi</h2><p>Gerçek şirket ve iletişim bilgileri olmadan örnek yasal metin yayımlamıyoruz.</p></div></Detail>}

function App(){const path=location.pathname.replace(/\/+$/,'')||'/';if(path==='/')return <Home/>;if(path==='/chatgpt-reklam-verme')return <Guide/>;if(path==='/iletisim')return <Contact/>;if(path==='/blog')return <Blog/>;if(path==='/gizlilik'||path==='/kvkk'||path==='/cerez-politikasi')return <Legal title={path==='/kvkk'?'KVKK Aydınlatma Metni':path==='/gizlilik'?'Gizlilik Politikası':'Çerez Politikası'}/>;const data=pages[path];return data?<GenericPage data={data}/>:<Detail eyebrow="404" title="Sayfa bulunamadı" summary="Aradığınız içerik taşınmış olabilir."><a className="button primary" href="/">Ana sayfaya dön</a></Detail>}
export default App
